name: my_device
description: Agile and easy access to device information and internet connection alerts
version: 0.0.8
homepage: https://github.com/DameAri/my_device

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^2.2.1
  device_info_plus: ^3.2.2
  handy_dialogs: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:


  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #

